-- Auto-generated by install.sh from UUID.json — do not edit manually.
-- Run in Supabase SQL Editor whenever UUIDs change.

drop policy if exists "notes: read"               on notes;
drop policy if exists "notes: editors cross-read" on notes;

create policy "notes: read"
  on notes for select
  using (
    auth.uid() = user_id
    or (
      auth.uid() in ('8728f128-be6f-47b7-bb39-e11dc622e937', '28efbd8b-8ad1-40d3-aa21-b7f6d61e3b58')
      and user_id  in ('8728f128-be6f-47b7-bb39-e11dc622e937', '28efbd8b-8ad1-40d3-aa21-b7f6d61e3b58')
    )
    or (
      is_public = true
      and user_id in ('8728f128-be6f-47b7-bb39-e11dc622e937', '28efbd8b-8ad1-40d3-aa21-b7f6d61e3b58')
    )
  );

drop policy if exists "notes: owner write" on notes;

create policy "notes: owner write"
  on notes for all
  using  (auth.uid() = user_id)
  with check (auth.uid() = user_id);
